package com.taskify.taskify.model;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    TOKEN_REFRESH,
    TASK_CREATE,
    TASK_UPDATE,
    TASK_DELETE,
    FOCUS_MODE_USAGE,
    STAGNANT_MODE_USAGE,
    DAILY_CHECK_IN_CREATE,
    DAILY_CHECK_IN_UPDATE,
    INTENT_BUCKET_CREATE,
    INTENT_BUCKET_DELETE
}
